### ISSUE TITLE
Metrics not submitted

### ISSUE THREAD

**Issue by luisabtrace** [dbader/node-datadog-metrics#106]
It seems like the `apiHost` option is being ignored and has been for a while. For us, this is really bad because it breaks metrics. I believe this has been fixed in `master` so, can you release a new version? If not, could you tell me what's the last version that works?

Thanks.

**Comment by Mr0grog** [comment]
@ErikBoesen @dbader the current state of `main` is a bit complicated — there are a) breaking changes, and b) a new bug (see #103). I think a fix for #103 needs to be added after commit e116612baaa8058807a4f9758b195480a5a1bfb8, and that should be released as v0.10.2 (that way there are no breaking changes).

**Comment by Mr0grog** [comment]
I went ahead and made a `v0.10.x` branch where the head is in the last position without breaking changes, and changed #103 to be set to merge into it. I’ll see about merging that PR, but I don’t have publishing rights on NPM.

**Comment by Mr0grog** [comment]
(Or you can add me as a maintainer on NPM. Same username as GitHub. 🤷)

**Comment by ErikBoesen** [comment]
I'm not able to add maintainers—could you do so @dbader ?

**Comment by dbader** [comment]
Yep, I just tried adding you @Mr0grog but it says user not found:

<img width="208" alt="Screen Shot 2022-10-14 at 4 19 32 PM" src="https://user-images.githubusercontent.com/306708/195956826-2ed18e7e-b930-419f-b106-ddb3505a15a0.png">

**Comment by Mr0grog** [comment]
Ahhhh, lower-case `m`, sorry.

**Comment by Mr0grog** [comment]
https://www.npmjs.com/~mr0grog

**Comment by Mr0grog** [comment]
I’ve merged in the bugfix, cleaned up release notes, set the version numbers, and [tagged v0.10.2 in git](https://github.com/dbader/node-datadog-metrics/tree/v0.10.2). A release can be published to NPM from that tag.

**Comment by dbader** [comment]
Ah, didn't realize NPM's user handles were case sensitive. Invite sent! ✅

**Comment by Mr0grog** [comment]
@luisabtrace this should be fixed in v0.10.2, which now available on NPM. There are a lot of updates in it that might be useful besides that bugfix — full release notes here: https://github.com/dbader/node-datadog-metrics/releases/tag/v0.10.2
