### ISSUE TITLE
Custom Timestamp of reported data

### ISSUE THREAD

**Issue by gnarf** [dbader/node-datadog-metrics#16]
I was trying to figure out how to add the ability to set the timestamp of some data.

I have a query that I'm charting that takes the sum of yesterdays values, but it always submits with todays timestamp, I'd like to be able to make it submit from the exact time of the "end of the reporting day"

**Comment by SomeoneWeird** [comment]
Any update on this? This would be really useful for us too.

**Comment by csabapalfi** [comment]
Fixed by #22. Thanks @ronny!
