### ISSUE TITLE
Multiple data points with different tags

### ISSUE THREAD

**Issue by a-rodin** [dbader/node-datadog-metrics#17]
I want to do something like this:

``` js
metrics.gauge('mymetric', 1.0, ['tag1'])
metrics.gauge('mymetric', 2.0, ['tag2'])
```

but it doesn't work because the second `gauge` call checks that "mymetric" point is already added and doesn't add it again. So the second metric becomes lost.

**Comment by csabapalfi** [comment]
This should not happen because of https://github.com/dbader/node-datadog-metrics/commit/004fa221aa8cf9dd9b1c7d563a79cb415fb5760f

See also the tests I added in #28

**Comment by csabapalfi** [comment]
Closing this now. Please re-open if you still see this problem.
