### ISSUE TITLE
Is this repo still maintained? Do you need any help?

### ISSUE THREAD

**Issue by csabapalfi** [dbader/node-datadog-metrics#21]
Thanks for building this module. Making great use of it!

I'd be more than happy to offer my help and review PRs etc. (e.g. I'd love to have #15 merged, also I'm thinking of replacing the histogram implementation with something more solid).

Alternatively I'll most likely go ahead and fork this repo but first wanted to get your thoughts.

Thanks,
Csaba

**Comment by dbader** [comment]
Hey @csabapalfi, sorry for my late response :) Glad you like the module. You know what I'd appreciate some help with this. If you're still interested I'll give you commit rights so we can move this forward together.

— Dan

**Comment by csabapalfi** [comment]
Brilliant, thanks! I'm still interested!

**Comment by dbader** [comment]
Great :) Invite sent! Feel free to reach out to me at mail@dbader.org any time. I'd also be happy to hop on Skype/Hangouts with you if it makes sense. We should be able to discuss most things via PRs and issues though :)

**Comment by csabapalfi** [comment]
Nice one! :+1: 

Will drop you an email with my contact details.

To be honest I also think issues and PRs should do the job most of the time. :)

Closing this one now.
