### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by csabapalfi** [dbader/node-datadog-metrics#23]
Hi @dbader,

Can you please release 0.4.0?

Alternatively I'm happy to release if you can add me here: https://www.npmjs.com/package/datadog-metrics/access

Thanks,
Csaba

**Comment by dbader** [comment]
Hey @csabapalfi, I've added you as a collaborator on npm. Release away :-) Thank you!

**Comment by dbader** [comment]
Btw please feel free to add your name to the README / contributors where you think it's appropriate.
