### ISSUE TITLE
increment(name, 0) results in a count of 1

### ISSUE THREAD

**Issue by haspriyank** [dbader/node-datadog-metrics#38]
bagi.js 
```
    "use strict"; 
    var metrics = require('datadog-metrics'); 
    function collectBagi() {  
        metrics.increment('bagi', 0);
    } 
    setInterval(collectBagi, 1000);
```

 ran it with `DATADOG_API_KEY="XXXXXXX" DEBUG=metrics node bagi.js`

here are the logs
<img width="875" alt="screen shot 2018-01-09 at 11 49 43 pm" src="https://user-images.githubusercontent.com/3229967/34761287-00e97218-f598-11e7-8540-b5a6b5582523.png">

and here is the datadog graph it produced
<img width="1653" alt="screen shot 2018-01-09 at 11 49 00 pm" src="https://user-images.githubusercontent.com/3229967/34761307-118bc90e-f598-11e7-86c1-4e6680eca4f7.png">

I was expecting nothing in the graph since the count is 0.

I believe this is because of https://github.com/dbader/node-datadog-metrics/blob/master/lib/loggers.js#L76

We should be doing this only if value is undefined. When value is 0 it should be treated as 0, and not changed to 1.

**Comment by csabapalfi** [comment]
Released in 0.8.1. Thanks for the PR!
