### ISSUE TITLE
Can't get custom timestamp to work

### ISSUE THREAD

**Issue by guzmo** [dbader/node-datadog-metrics#40]
Hey,

I'm trying to add historical data to Datadog.
When I'm sending a timestamp as the last parameter, nothing shows up in Datadog, only "newer" data then current time.
```
metrics.increment(results[i].id, results[i].value, results[i].tags, results[i].time);
```
If it is a bug in Datadog itself or something wrong with this library, I'm not sure.

Any feedback would be appreciated!
Cheers!

**Comment by guzmo** [comment]
Found out Datadog doesn't support it, which is really bad, but not a problem with this library

**Comment by csabapalfi** [comment]
Thanks for resolving this! Might still need to remove timestamps from the API then or at least document this to avoid confusion

I’ll try and look into this myself as well.

**Comment by guzmo** [comment]
Well, they support 10 min in to the future and 1 hour in the past. So, they support it, but not as far as I would like :)

**Comment by csabapalfi** [comment]
I see, thanks for clarifying!
