### ISSUE TITLE
Support Browser usage

### ISSUE THREAD

**Issue by rue-bwebb** [dbader/node-datadog-metrics#43]
Right now the only thing preventing this library from being usable in modern browsers natively is the call to `tid.unref` in the logger. Could we get this line changed to something like `tid.unref && tid.unref()`?

**Comment by Mr0grog** [comment]
@rue-bwebb The specific issue you noted (`timer.unref()`) will be fixed as soon as the next release is published, although we aren’t actively testing or maintaining for browser-based usage. If you’re still trying to use (or using) this in a browser, please give the code on the `main` branch a try and post back here if you hit other problems.
