### ISSUE TITLE
support distributions

### ISSUE THREAD

**Issue by theburningmonk** [dbader/node-datadog-metrics#46]
Now that Datadog [supports](https://docs.datadoghq.com/developers/metrics/distributions/) `distribution` metric type, would be good for the library to support it too.

**Comment by PatrykMilewski** [comment]
I think that DataDog doesn't provide any official documentation about accessing distribution metric type through their API.

It's possible to find how to use it by looking into their Lambda Layers repos:
https://github.com/DataDog/datadog-lambda-layer-js/blob/master/src/metrics/api.ts
