### ISSUE TITLE
Ability to select which histogram metrics to send

### ISSUE THREAD

**Issue by Shahor** [dbader/node-datadog-metrics#48]
To offer a bit more control on metrics volume it would be interesting to offer a way to select which kind of metrics we want the histogram to produce.

**Comment by gquinteros93** [comment]
Hi, I created a [PR](https://github.com/dbader/node-datadog-metrics/pull/64) to enable that feature 😄 
I hope the library maintainers can review it soon 🙏

**Comment by ErikBoesen** [comment]
Thanks!

**Comment by gquinteros93** [comment]
Hi @ErikBoesen , thanks for reviewing the PR and merging it.
Do you have an idea when a new version of the library would be released with this new feature?

**Comment by gquinteros93** [comment]
Hi @ErikBoesen , thank you for uploading version 0.10.0

Soon I will create a new PR to update the library docs and include the feature to choose which aggregates and percentiles to use in the Histogram. 

I will do it after fixing this [issue](https://github.com/dbader/node-datadog-metrics/issues/65) (for which I've already created a [PR](https://github.com/dbader/node-datadog-metrics/pull/66))
