### ISSUE TITLE
Auto Flush with flushIntervalSeconds not working

### ISSUE THREAD

**Issue by ZehuaZhang** [dbader/node-datadog-metrics#49]
It seems that instantiating Metric with `flushIntervalSeconds` via `BufferedMetricsLogger()` is not working. Auto flush never triggered after specified intervals.

Need to force a `flush()` everytime a metric is sent.

Package updated to latest.

**Comment by ZehuaZhang** [comment]
`BufferedMetricsLogger` is constructed with invalid config

**Comment by csabapalfi** [comment]
@ZehuaZhang thanks for reporting the issue then closing it. 

Can you share how it `BufferedMetricsLogger` was misconfigured? Was that something that clearer documentation maybe help others avoid in the future? 

Thanks!
