### ISSUE TITLE
Make errors more obvious

### ISSUE THREAD

**Issue by mjaverto** [dbader/node-datadog-metrics#52]
After getting no data errors this morning from Datadog, I found ```metrics ERROR: add_metrics failed: null (err=Error: certificate has expired, status=0) +324ms``` with DEBUG mode enabled.

I'd think this should fire an error, not just a debug log.

**Comment by Mr0grog** [comment]
@mjaverto would allowing you to add an error handler have helped solved this for you? For example, if you could have done:

```js
const metrics = require('datadog-metrics');
metrics.init({
  onError (error) {
    // Whatever logic you want to respond to errors.
    // Could log to the console, send an error to a bug tracker like Sentry, etc.
    console.error("Error from datadog-metrics:", error);
  }
});
```
