### ISSUE TITLE
How to upload to datadoghq.eu?

### ISSUE THREAD

**Issue by dennisbrouwer91** [dbader/node-datadog-metrics#58]
Hi,

I have a Datadog account on the EU cluster, not the US one. Is there any way to send metrics to the datadoghq.eu domain instead of datadoghq.com ?

**Comment by thatguychrisw** [comment]
You can set `DATADOG_API_HOST` to that value.  The reporter uses that env variable under the hood.

**Comment by ErikBoesen** [comment]
In the newest release it's now possible to pass the parameter `apiHost` to the initialization of `DataDogReporter` specifying a custom host.
