### ISSUE TITLE
🚨 Bug introduced in 0.9.0 related to setting the api host

### ISSUE THREAD

**Issue by thatguychrisw** [dbader/node-datadog-metrics#61]
@ErikBoesen adding the [host to the reporter](https://github.com/dbader/node-datadog-metrics/blob/master/lib/reporters.js#L29-L36) I _think_ introduced a breaking change.  If the environment variable is not set it passes on `undefined` to `dogapi.initialize()` which results in the host being set to localhost instead of `app.datadoghq.com`.

**Comment by RobvH** [comment]
Am also experiencing this.

**Comment by eliurkis** [comment]
Me too!

**Comment by thatguychrisw** [comment]
@ErikBoesen happy to submit a PR if you have an idea of how you want to handle this.

**Comment by ErikBoesen** [comment]
Thanks for the report, I've just rolled out version 0.9.1 to fix this issue. Feel free to reopen if that does not fix your problem.

**Comment by thatguychrisw** [comment]
Thanks @ErikBoesen!
