### ISSUE TITLE
Does the latest version include my merged changes?

### ISSUE THREAD

**Issue by thatguychrisw** [dbader/node-datadog-metrics#63]
Has there been an NPM release since my merge in October of last year?  Can't find a way to confirm and our teams are still using a hardcoded reference.

**Comment by thatguychrisw** [comment]
This is the [PR](https://github.com/dbader/node-datadog-metrics/pull/62)

**Comment by gquinteros93** [comment]
Hi @thatguychrisw , Yes, your PR was merged and released in version 0.10.0

However, that new version introduced the following error: [Version 0.10.0 datadogApiClient.createConfiguration is not a function](https://github.com/dbader/node-datadog-metrics/issues/65)

I've created a [PR](https://github.com/dbader/node-datadog-metrics/pull/66) to fix that issue.

Could you confirm that the PR solution works well for you too?

**Comment by ErikBoesen** [comment]
All merged changes are incorporated in version 0.10.1.
