### ISSUE TITLE
Version 0.10.0 datadogApiClient.createConfiguration is not a function

### ISSUE THREAD

**Issue by gquinteros93** [dbader/node-datadog-metrics#65]
### Issue

The new version 0.10.0 contains the following error:

![image](https://user-images.githubusercontent.com/53574912/189501974-f253f4df-da5b-4218-9369-2eac9ac41c5a.png)

### Cause

As we can see in the following screenshot, the version of `datadog-api-client-typescript` installed is 1.3.0

![image](https://user-images.githubusercontent.com/53574912/189520666-b3859d24-8a7d-414e-8365-b427441fbc9d.png)

If we check the [documentation](https://github.com/DataDog/datadog-api-client-typescript#getting-started) of datadog-api-client-typescript`version 1.3.0 

![image](https://user-images.githubusercontent.com/53574912/189520899-0b95d22f-2a83-416f-bcb3-157d7b9455f4.png)

The `createConfiguration` function comes from `client` while the `MonitorsApi` comes from `v1`.

However, `node-datadog-metrics` are using `createConfiguration` and `MetricsApi` both from `v1` in the [reporters.js](https://github.com/dbader/node-datadog-metrics/blob/4c29447bbde00565d5258e722b147601f3cc014c/lib/reporters.js#L3):

![image](https://user-images.githubusercontent.com/53574912/189521048-fa55b623-8b03-40ae-a390-50d5e7b994b2.png)

![image](https://user-images.githubusercontent.com/53574912/189521060-3bbebdbf-9b66-4e61-848e-2ca08389235d.png)

### Possible Solution

I believe the solution would be to import the `MetricsApi` from `v1` and the `createConfiguration` from `client`.

I will create a PR soon to fix this issue.

**Comment by gquinteros93** [comment]
I've just created a [PR](https://github.com/dbader/node-datadog-metrics/pull/66) with the fix to this issue.

**Comment by ErikBoesen** [comment]
Merged and released 0.10.1.
