### ISSUE TITLE
Add median for histogram metrics

### ISSUE THREAD

**Issue by Mr0grog** [dbader/node-datadog-metrics#68]
When using DogStatsD, the histogram type calculates a `<metric_name>.median` metric that this package does not. It would be great to add that here.

(Context: I’m experimenting with transitioning an app from DogStatsD to this for an environment where the other system/host metrics DogStatsD collects aren’t needed, so we can reduce configuration overhead and cost.)

I’d be happy to submit a PR to add this, if helpful.

**Comment by ErikBoesen** [comment]
Sounds good, feel free to make a PR!

**Comment by Mr0grog** [comment]
Done! #69.
