### ISSUE TITLE
Change default branch name to `main`

### ISSUE THREAD

**Issue by Mr0grog** [dbader/node-datadog-metrics#75]
It would be good to switch the default branch name here to `main`, which is a more inclusive term (and is also now the default for new repos on GitHub). This is a continuation from a brief discussion on the co-maintainers issue: https://github.com/dbader/node-datadog-metrics/issues/55#issuecomment-1251689164

**Comment by Mr0grog** [comment]
@ErikBoesen are you good with this, and do you have access to the settings panel to make that change? Looks like I don’t — it’s under “Settings” (top tabs) → “Branches” (sidebar).

*Renaming* the branch will update existing pull requests, protection rules etc. IIRC it will also cause URLs for the old branch name to redirect, but I don’t remember for sure (e.g. `https://github.com/dbader/node-datadog-metrics/blob/master/index.js` → `https://github.com/dbader/node-datadog-metrics/blob/main/index.js`).

An alternative is to split off a new `main` branch, switch the default branch to it, and add a notice to the top of the README on the `master` branch that explains it is for archival/old links purposes only (here’s an example from a larger public project I maintain: https://github.com/edgi-govdata-archiving/web-monitoring/tree/master#readme).

**Comment by Mr0grog** [comment]
From the original discussion…

> I'm onboard with that, as long as someone makes sure CI and npm deploys still work.

@dbader Am I understanding right that Travis is no longer running CI for this (since they stopped doing free for open-source on travis-ci.org) and the only CI is the GitHub workflow added in #74?

Is there a script or service doing deploys somewhere that might need updating, or is that manual?

**Comment by ErikBoesen** [comment]
I don't have permissions to change settings of the repo, including the default branch name. @dbader will need to do it.

**Comment by Mr0grog** [comment]
@dbader Could you please make this change, or temporarily give me admin privileges to do so?

- Let me know if there’s any script or tooling for NPM publishing I need to check, but if you’re just doing it manually, branch names shouldn’t factor into it.
- The new GitHub CI stuff runs on every push to every branch right now, so there should be no issues there: https://github.com/dbader/node-datadog-metrics/blob/13b8e1eb51b95180bc8135c7a8f98552a0bea9be/.github/workflows/ci.yml#L1-L3

**Comment by Mr0grog** [comment]
I also checked the docs on renaming, and I remembered correctly — it does do redirects. So any links to `master` will redirect to `main`: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch

**Comment by dbader** [comment]
> @dbader Am I understanding right that Travis is no longer running CI for this (since they stopped doing free for open-source on travis-ci.org) and the only CI is the GitHub workflow added in #74?

Yep that's correct, I believe we no longer use Travis for anything. The build status badge in the README still references TravisCI: https://github.com/dbader/node-datadog-metrics/blob/13b8e1eb51b95180bc8135c7a8f98552a0bea9be/README.md?plain=1#L5

Maybe there's a way to do badges with the Github Actions CI integration, or we can remove it.

**Comment by Mr0grog** [comment]
Done in #76.

**Comment by Mr0grog** [comment]
Closing this. I think we've taken care of everything.
